def build(bld):
    bld.program(
        source      = bld.path.ant_glob([ 'src/*.l', 'src/*.y', 'src/*.c', 'src/**/*.c' ]),
        includes    = ['include', '../ex86/include'],
        target      = 'iex86',
        use         = ['ex86'])
